// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR-JAi9_UC28La9CBzyM1g0ie4s4j3adY',
    appId: '1:896657963986:web:3b23ea3dab2aa66193260b',
    messagingSenderId: '896657963986',
    projectId: 'mannpakad',
    authDomain: 'mannpakad.firebaseapp.com',
    databaseURL: 'https://mannpakad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mannpakad.firebasestorage.app',
    measurementId: 'G-55ZVC4Z7NW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7V4uBrONzORbdfX42Y6IV-CUXIWjGapI',
    appId: '1:896657963986:android:6f56f9706115caab93260b',
    messagingSenderId: '896657963986',
    projectId: 'mannpakad',
    databaseURL: 'https://mannpakad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mannpakad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvCHrgr0PDDvC_ewBcFffBFMdb9DLGZyo',
    appId: '1:896657963986:ios:cbffff1de551cf4393260b',
    messagingSenderId: '896657963986',
    projectId: 'mannpakad',
    databaseURL: 'https://mannpakad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mannpakad.firebasestorage.app',
    iosBundleId: 'com.example.mannpakad',
  );

}